name: Daily Commit Workflow

on:
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # VERY IMPORTANT: Grants write access to the repository content

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Commit changes by 24ds2000134@ds.study.iitm.ac.in
        run: |
          echo "Daily commit on $(date)" >> daily_commit_log.txt
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "24ds2000134@ds.study.iitm.ac.in"
          git add daily_commit_log.txt
          git commit -m "Daily commit on $(date)"
          git push
